# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{b53a0377-bb3f-49d6-a9c7-58a83ac1dae2}',
        'contract_ids': ['@mozilla.org/zen/command-line-handler;1'],
        'esModule': 'resource:///modules/ZenCommandLineHandler.sys.mjs',
        'constructor': 'ZenCommandLineHandler',
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
        'categories': {'command-line-handler': 'm-zen'},
    },
]
